import { useState } from 'react';
import { Link } from 'react-router-dom';
import DemoRequestForm from '../components/DemoRequestForm';

const plans = [
  { name: 'Core', monthly: 79, annual: 790, fit: 'Independent mosque', description: 'The complete Friday workflow for one site.', features: ['1 live room and all connected screens', '3 simultaneous display languages', 'Friday readiness and display test', 'Prayer and standby display modes', 'Mosque terminology setup', 'Email and WhatsApp support'], recommended: true },
  { name: 'Pro', monthly: 149, annual: 1490, fit: 'Central mosque or Islamic centre', description: 'More services, languages and operational support.', features: ['Everything in Core', '6 simultaneous display languages', 'Livestream caption overlay', 'Announcement and event screen modes', 'Khutbah transcript workspace when released', 'Priority Friday support'] },
  { name: 'Network', monthly: 399, annual: 3990, fit: 'Multi-site organisation', description: 'Central control and consistent language across sites.', features: ['3 sites included', 'Central settings and glossary', 'Cross-site readiness view', 'Role-based operations', 'Quarterly translation-quality review', 'Rollout and support plan'] },
];

export default function PricingPage() {
  const [annual, setAnnual] = useState(true);
  return (
    <div className="min-h-screen bg-[#08131F] text-[#F4EDDF]">
      <nav className="border-b border-[#88CED0]/10"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 md:px-8"><Link to="/" className="font-editorial text-xl font-bold">khutba<span className="text-[#88CED0]">.io</span></Link><Link to="/demo" className="rounded-full border border-[#D6A64A]/45 px-4 py-2 text-sm font-semibold text-[#F0C978]">Try demo</Link></div></nav>

      <header className="tile-pattern border-b border-[#88CED0]/10 py-20 text-center md:py-28"><div className="mx-auto max-w-4xl px-5"><p className="text-xs font-bold uppercase tracking-[.28em] text-[#88CED0]">Annual contracts built for dependable Fridays</p><h1 className="font-editorial mt-6 text-5xl leading-tight md:text-6xl">Price the outcome, not every minute spoken.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[#E7D6B5]/65">Start with a four-Friday pilot. Subscribe when the workflow works in your building, with your imam, audio and screens.</p><div className="mx-auto mt-9 inline-flex rounded-full border border-[#88CED0]/18 bg-[#0B1B2A] p-1"><button onClick={() => setAnnual(false)} className={`rounded-full px-5 py-2 text-sm ${!annual ? 'bg-[#F4EDDF] font-bold text-[#08131F]' : 'text-[#E7D6B5]/55'}`}>Monthly</button><button onClick={() => setAnnual(true)} className={`rounded-full px-5 py-2 text-sm ${annual ? 'bg-[#D6A64A] font-bold text-[#08131F]' : 'text-[#E7D6B5]/55'}`}>Annual · save 2 months</button></div></div></header>

      <main className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28">
        <div className="grid gap-5 lg:grid-cols-3">{plans.map(plan => <article key={plan.name} className={`relative flex flex-col rounded-2xl border p-6 md:p-8 ${plan.recommended ? 'border-[#D6A64A]/55 bg-[#123E73]/20' : 'border-[#88CED0]/16 bg-[#0B1B2A]/55'}`}>{plan.recommended && <span className="absolute right-6 top-0 -translate-y-1/2 rounded-full bg-[#D6A64A] px-3 py-1 text-[10px] font-bold uppercase tracking-[.18em] text-[#08131F]">Best first contract</span>}<p className="text-xs font-bold uppercase tracking-[.22em] text-[#88CED0]">{plan.fit}</p><h2 className="font-editorial mt-4 text-3xl">{plan.name}</h2><p className="mt-3 min-h-12 text-sm leading-6 text-[#E7D6B5]/55">{plan.description}</p><div className="mt-7 border-y border-[#88CED0]/10 py-5"><span className="font-editorial text-4xl text-[#F0C978]">£{annual ? plan.annual : plan.monthly}</span><span className="text-sm text-[#E7D6B5]/45"> / {annual ? 'year' : 'month'}</span>{annual && <p className="mt-1 text-xs text-[#88CED0]/65">Equivalent to £{Math.round(plan.annual / 12)}/month, billed once</p>}</div><ul className="mt-6 flex-1 space-y-3 text-sm text-[#E7D6B5]/72">{plan.features.map(feature => <li key={feature} className="flex gap-3"><span className="text-[#D6A64A]">✓</span>{feature}</li>)}</ul><a href="#pilot" className={`mt-8 rounded-full px-5 py-3 text-center font-bold ${plan.recommended ? 'bg-[#D6A64A] text-[#08131F]' : 'border border-[#88CED0]/28 text-[#F4EDDF]'}`}>Start with a pilot</a></article>)}</div>

        <section className="mt-16 grid gap-6 border-y border-[#88CED0]/12 py-10 md:grid-cols-3"><div><p className="font-semibold">4-Friday pilot</p><p className="mt-2 text-sm leading-6 text-[#E7D6B5]/50">No payment while we prove audio, latency, readability and volunteer workflow.</p></div><div><p className="font-semibold">Usage policy</p><p className="mt-2 text-sm leading-6 text-[#E7D6B5]/50">Plans cover normal mosque services. High-volume conferences, broadcasters and Ramadan programmes receive a clear capacity quote—never a mid-khutbah cutoff.</p></div><div><p className="font-semibold">Optional Khutba Box</p><p className="mt-2 text-sm leading-6 text-[#E7D6B5]/50">Browser use remains standard. A managed HDMI device will be offered only where it materially improves reliability.</p></div></section>

        <section id="pilot" className="mt-24 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-[#88CED0]">Start with evidence</p><h2 className="font-editorial mt-5 text-4xl leading-tight">Four Fridays. A real committee decision.</h2><p className="mt-5 leading-7 text-[#E7D6B5]/58">Annual prepayment is earned after the product works in your mosque. The pilot review covers successful minutes, readability, volunteer effort and congregation feedback.</p></div><DemoRequestForm /></section>
      </main>
    </div>
  );
}
